services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./vector_db:/app/vector_db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/document_analyzer
      - OS_TYPE=windows
    env_file:
      - .env  # Загружаем .env с хоста
    depends_on:
      db:
        condition: service_healthy
    cap_add:
      - NET_ADMIN  # Необходимо для работы с сетевыми настройками для OpenVPN
    privileged: true  # Дает дополнительные привилегии для работы с сетевыми интерфейсами
    sysctls:
      - net.ipv4.ip_forward=1  # Включение перенаправления IP для VPN
    dns:
      - 8.8.8.8  # Google DNS
      - 1.1.1.1  # Cloudflare DNS
    # Оптимизации для Windows
    command: sh -c "export WINDOWS_MODE=true && /app/start.sh"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=document_analyzer
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5052:80"
    depends_on:
      - db

volumes:
  postgres_data: 